sudo: required
services:
  - docker

before_install:
  - docker build -t vinothrallapalli/react-app -f Dockerfile.dev .

script:
    - docker run vinothrallapalli/react-app npm run test -- --coverage
